[providers]
python = "3.11"

[variables]
NIXPACKS_NO_CACHE = "1"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["cd backend", "pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python backend build complete'"]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"