providers = ["python"]

[variables]
NIXPACKS_NO_CACHE = "1"
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "cd backend",
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Python backend build complete'"]

[start]
cmd = "cd backend && /opt/venv/bin/python -m uvicorn main:app --host 0.0.0.0 --port $PORT"