[providers]
# Force Python detection, ignore Node.js
python = "*"

[phases.setup]
nixPkgs = ["python3", "pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python backend ready'"]

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"