[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
# OpenAI Embedding Model
OPENAI_EMBEDDING_MODEL = "text-embedding-3-large"

# Zilliz Configuration
ZILLIZ_COLLECTION_NAME = "openai_embeddings"

# Search config
TOP_K = "8"

# CORS
CORS_ORIGINS = "https://kia8804.github.io,http://localhost:5173"
API_PREFIX = "/api"

# Note: ZILLIZ_URI and ZILLIZ_TOKEN must be set manually in Railway dashboard
# Note: OPENAI_API_KEY not needed - users enter in UI